name: Update Packagist Package

on: 
  push:
    tags:
      - '*'

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist Package
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
        run: |
          if [ -z "$PACKAGIST_USERNAME" ] || [ -z "$PACKAGIST_API_TOKEN" ]; then
            echo "Error: PACKAGIST_USERNAME or PACKAGIST_API_TOKEN is not set in secrets."
            exit 1
          fi

          REPO_URL="https://github.com/${{ github.repository }}"

          curl -X POST \
            -H "Content-Type: application/json" \
            "https://packagist.org/api/update-package?username=$PACKAGIST_USERNAME&apiToken=$PACKAGIST_API_TOKEN" \
            -d "{\"repository\":\"$REPO_URL\"}"
